//cac thong bao
module.exports = {
  ERROR_MESSAGE: {
    INDEX: {
      EXIST: "INDEX_EXIST",
      NOT_FOUND: "INDEX_NOT_EXIST",
      EMPTY: "INDEX_EMPTY",
      EMPTY_EXPIRATION_DATE: "EMPTY_EXPIRATION_DATE",
      EMPTY_RENTER: "EMPTY_RENTER",
      EMPTY_CAR_NUMBER: "EMPTY_CAR_NUMBER",
      NOT_STANDARD: "NONSTANDARD_EXPIRATION_DATE"
    },
    ROOM_TICKET: {
      EXIST: "ROOM_TICKET_EXIST",
      NOT_FOUND: "ROOM_TICKET_NOT_EXIST",
      FAIL_DELETE: "ROOM_DELETE_FAIL",
      FAIL_UPDATE: "ROOM_UPDATE_FAIL",
      CREATE_FAIL: "CREATE_ROOM_FAIL"
    },
    USER: {
      EXIST: "USER_EXIST",
      NOT_FOUND: "USER_NOT_EXIST",
      WRONG_PASS: "WRONG_PASSWORD",
      EMPTY_NAME: "EMPTY_NAME",
      NOT_STANDARD: {
        PASS: "NONSTANDARD_PASSWORD",
        EMAIL: "NONSTANDARD_EMAILS"
      }
    }
  },
  SUCCESS_MESSAGE: {
    INDEX: {
      RENTED: "INDEX_RENTED",
      DELETED: "INDEX_DELETED"
    },
    ROOM_TICKET: {
      PASS_CREATE: "ROOM_TICKET_CREATE_SUCCESS"
    },
    USER: {
      CREATED: "USER_CREATED",
      DELETED: "USER_DELETED",
      LOGIN: "LOGIN_SUCCESS",
      CHANGE: {
        PASS: "PASS_CHANGED",
        INFO: "INFO_CHANGED"
      }
    }
  }
};
